premiosplatziapp/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    #     ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    #    ex: /polls/5/
    #    '<int:question_id>/' -> views based function 
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #    ex: /polls/5/results
    #    '<int:question_id>/results' -> views based function 
    path('<int:pk>/results', views.ResultView.as_view(), name='results'),
    #    ex: /polls/5/votes
    path('<int:question_id>/votes', views.votes, name='votes'),
]

premiosplatziapp/premiosplatziapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')), 
]

premiosplatziapp/polls/models.py
from secrets import choice
import datetime
from django.db import models
from django.utils import timezone

# Create your models here. 

class Question(models.Model):
    question_text = models.CharField(max_length=200) 
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text 

    def was_published_recently(self):
        return  timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1) 


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __self__(self):
        return self.choice_text 

premiosplatziapp/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse 
from django.views import generic
from django.utils import timezone 

'''
def index(request):
    latest_question_list = Question.objects.all() #esto trae un objeto de tipo 'queryset' 
    return render(request, 'polls/index.html', {
    #          key            :        value
        'latest_question_list': latest_question_list
    })    
 

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {
        'question': question
    }) 


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id) 
    return render(request, 'polls/results.html',{
        'question': question  
    }) '''

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        ''''Return the last five published questions'''
        return Question.objects.filter(pub_date__lte = timezone.now()).order_by('-pub_date')[:5] 


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self): 
        """
        Excludes any questions that aren't published yet 
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html' 


def votes(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question':question,
            'error_message': 'No ha seleccionado una respuesta.' 
        })
    else:
        selected_choice.votes += 1 
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

premiosplatziapp/polls/templates/polls/detail.html
<!--h1>TEST INITIAL TEMPLATE</!h1-->

<!--h1>{{ question.question_text }}</!h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li> 
    {%  endfor %} 
</ul-->

<form action="{% url 'polls:votes' question.id %}" method='post'>
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
        <input 
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}"
        > 
        <label for="choice{{ forloop.counter }}">
            {{choice.choice_text}}
        </label>
        <br>
        {%  endfor %}
    </fieldset>
    <br>
    <input type="submit" value="votar"> 
</form> 

premiosplatziapp/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<fieldset class="container">

{% if latest_question_list %}

<ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul> 

{% else %}

<h1>No polls are available.</h1>

{% endif %}

</fieldset>

premiosplatziapp/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">¿Te gustaría votar de nuevo?</a>